version: "3.7"

services:
    app:
        build: .
        container_name: rentx
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
